### ISSUE TITLE
Initial build from cloned repo fails to get 'chumsky' as a dependency

### ISSUE THREAD

**Issue by MayNc10** [JohnDowson/rotth#2]
When cloning the repo directly into a new folder, cargo build fails because the Cargo.toml specifies that chumsky should be provided as a local file ("chumsky = { path = "chumsky" }"), but the local file for chumsky is not included in the repo. If the line is changed so that it pulls from chumsky 0.8.0, the build also fails.

**Comment by JohnDowson** [comment]
Oh right, I was using a custom-patched `chumsky`, the feature was since implemented on master so I have now changed over using it as a git dependency, which should allow you to build Rotth without further issues.
